version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: feed_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: feed_db
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: admin123
      MB_DB_HOST: postgres
