# Generated by Django 5.2 on 2025-05-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usersessionview'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
